#!/usr/bin/env python3
"""
Test script to extract and inspect actual prompts generated by workflows.
This helps verify that prompts contain expected content (previous outputs, terminology, etc.).

Usage:
    python tests/test_prompt_extraction.py --workflow ADT_multi_agents --save-prompts
"""

import argparse
import sys
import json
from pathlib import Path
from datetime import datetime

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from workflows import WORKFLOW_REGISTRY
from workflows.ADT_multi_agents import (
    render_discourse_agent_prompt,
    render_translation_agent_prompt,
    render_memory_agent_prompt
)
from workflows.SbS_step_by_step import (
    render_research_prompt,
    render_draft_prompt,
    render_refinement_prompt,
    render_proofread_prompt
)
from workflows.MAATS_multi_agents import (
    render_dimension_prompt,
    render_refine_prompt
)
from utils import render_translation_prompt, format_terminology_dict, filter_terminology_by_source_text
from vars import language_id2name

# Test data
TEST_SOURCE_TEXT = "The United Nations (UN) is an international organization. It was founded in 1945. The UN promotes peace and security worldwide."
TEST_TERMINOLOGY = {
    "United Nations": ["联合国", "UN"],
    "international organization": ["国际组织"],
    "peace and security": ["和平与安全"]
}


def extract_sbs_prompts():
    """Extract all prompts from SbS workflow."""
    prompts = {}
    
    # Research
    research_prompt = render_research_prompt(TEST_SOURCE_TEXT, "en", "zh")
    prompts["research"] = research_prompt
    
    # Simulate outputs
    research_output = "This text discusses the United Nations organization and its founding."
    draft_output = "联合国（UN）是一个国际组织。它成立于1945年。"
    refinement_output = "联合国（UN）是一个国际组织。它成立于1945年。联合国促进世界和平与安全。"
    
    # Draft
    draft_prompt = render_draft_prompt(TEST_SOURCE_TEXT, research_output)
    prompts["draft"] = draft_prompt
    
    # Refinement
    refinement_prompt = render_refinement_prompt(draft_output)
    prompts["refinement"] = refinement_prompt
    
    # Proofreading
    proofread_prompt = render_proofread_prompt(
        TEST_SOURCE_TEXT, draft_output, refinement_output
    )
    prompts["proofread"] = proofread_prompt
    
    return prompts


def extract_maats_prompts():
    """Extract all prompts from MAATS workflow."""
    prompts = {}
    
    # Initial translation
    translation_prompt = render_translation_prompt(
        TEST_SOURCE_TEXT, "en", "zh", language_id2name,
        use_terminology=False, terminology=None, max_terms=50
    )
    prompts["initial_translation"] = translation_prompt
    
    # Simulate translation
    initial_translation = "联合国（UN）是一个国际组织。它成立于1945年。联合国促进世界和平与安全。"
    
    # Dimension prompts
    for dimension in ["terminology", "accuracy", "style"]:
        dim_prompt = render_dimension_prompt(
            dimension, TEST_SOURCE_TEXT, initial_translation, "en", "zh"
        )
        prompts[f"dimension_{dimension}"] = dim_prompt
    
    # Simulate annotations
    annotations = {
        "terminology": "[Major]: [terminology/wrong_term] - Example",
        "accuracy": "[Minor]: [accuracy/error_subcategory] - None",
        "style": "[Critical]: [style/error_subcategory] - None"
    }
    
    # Refinement
    refine_prompt = render_refine_prompt(
        TEST_SOURCE_TEXT, initial_translation, annotations, "en", "zh"
    )
    prompts["refinement"] = refine_prompt
    
    return prompts


def extract_adt_prompts():
    """Extract all prompts from ADT workflow."""
    prompts = {}
    
    # Discourse agent
    current_discourse = "The United Nations (UN) is an international organization."
    next_sentence = "It was founded in 1945."
    discourse_prompt = render_discourse_agent_prompt(
        current_discourse, next_sentence, "en", 1024
    )
    prompts["discourse_agent"] = discourse_prompt
    
    # Memory
    memory = {
        "proper_noun_references": {"United Nations": "联合国", "UN": "UN"},
        "phrase_consistency": {"international organization": "国际组织"},
        "discourse_markers": []
    }
    discourse = "The United Nations (UN) is an international organization. It was founded in 1945."
    
    # Translation without terminology
    translation_prompt = render_translation_agent_prompt(
        discourse, memory, "en", "zh", None, False
    )
    prompts["translation_agent_no_term"] = translation_prompt
    
    # Translation with terminology
    formatted_term = format_terminology_dict(TEST_TERMINOLOGY, "en", "zh", max_terms=50)
    filtered_term = filter_terminology_by_source_text(formatted_term, discourse, case_sensitive=False)
    translation_prompt_term = render_translation_agent_prompt(
        discourse, memory, "en", "zh", filtered_term, True
    )
    prompts["translation_agent_with_term"] = translation_prompt_term
    
    # Memory agent
    target_discourse = "联合国（UN）是一个国际组织。它成立于1945年。"
    memory_prompt = render_memory_agent_prompt(memory, discourse, target_discourse)
    prompts["memory_agent"] = memory_prompt
    
    return prompts


def analyze_prompt(prompt_name: str, prompt_text: str, expected_content: list):
    """Analyze a prompt to check for expected content."""
    print(f"\n[{prompt_name}]")
    print(f"  Length: {len(prompt_text)} chars")
    print(f"  Lines: {len(prompt_text.split(chr(10)))}")
    
    # Check for expected content
    found = []
    missing = []
    for content in expected_content:
        if content in prompt_text:
            found.append(content)
        else:
            missing.append(content)
    
    if found:
        print(f"  ✓ Found: {len(found)}/{len(expected_content)} expected items")
        for item in found[:3]:  # Show first 3
            print(f"    - '{item[:50]}...'")
    if missing:
        print(f"  ✗ Missing: {len(missing)}/{len(expected_content)} expected items")
        for item in missing[:3]:  # Show first 3
            print(f"    - '{item[:50]}...'")
    
    return len(missing) == 0


def main():
    parser = argparse.ArgumentParser(description="Extract and analyze workflow prompts")
    parser.add_argument("--workflow", type=str, default="all",
                        help=f"Workflow to extract prompts from. Available: {list(WORKFLOW_REGISTRY.keys())} or 'all'")
    parser.add_argument("--save-prompts", action="store_true",
                        help="Save extracted prompts to JSON file")
    
    args = parser.parse_args()
    
    print("="*80)
    print("PROMPT EXTRACTION AND ANALYSIS")
    print("="*80)
    
    all_prompts = {}
    
    if args.workflow.lower() == "all" or args.workflow == "SbS_step_by_step":
        print("\nExtracting SbS_step_by_step prompts...")
        sbs_prompts = extract_sbs_prompts()
        all_prompts["SbS_step_by_step"] = sbs_prompts
        
        # Analyze
        print("\nAnalyzing SbS prompts...")
        analyze_prompt("research", sbs_prompts["research"], [TEST_SOURCE_TEXT])
        analyze_prompt("draft", sbs_prompts["draft"], [TEST_SOURCE_TEXT, "This text discusses"])
        analyze_prompt("refinement", sbs_prompts["refinement"], ["联合国（UN）是一个国际组织"])
        analyze_prompt("proofread", sbs_prompts["proofread"], [TEST_SOURCE_TEXT, "联合国（UN）"])
    
    if args.workflow.lower() == "all" or args.workflow == "MAATS_multi_agents":
        print("\nExtracting MAATS_multi_agents prompts...")
        maats_prompts = extract_maats_prompts()
        all_prompts["MAATS_multi_agents"] = maats_prompts
        
        # Analyze
        print("\nAnalyzing MAATS prompts...")
        analyze_prompt("initial_translation", maats_prompts["initial_translation"], [TEST_SOURCE_TEXT])
        analyze_prompt("dimension_terminology", maats_prompts["dimension_terminology"], [TEST_SOURCE_TEXT])
        analyze_prompt("refinement", maats_prompts["refinement"], [TEST_SOURCE_TEXT, "terminology", "accuracy"])
    
    if args.workflow.lower() == "all" or args.workflow == "ADT_multi_agents":
        print("\nExtracting ADT_multi_agents prompts...")
        adt_prompts = extract_adt_prompts()
        all_prompts["ADT_multi_agents"] = adt_prompts
        
        # Analyze
        print("\nAnalyzing ADT prompts...")
        analyze_prompt("discourse_agent", adt_prompts["discourse_agent"], ["United Nations", "founded"])
        analyze_prompt("translation_agent_no_term", adt_prompts["translation_agent_no_term"], ["United Nations", "memory"])
        analyze_prompt("translation_agent_with_term", adt_prompts["translation_agent_with_term"], ["United Nations", "terminology", "联合国"])
        analyze_prompt("memory_agent", adt_prompts["memory_agent"], ["United Nations", "联合国"])
    
    # Save prompts if requested
    if args.save_prompts:
        output_file = Path(__file__).parent / f"extracted_prompts_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        with open(output_file, "w", encoding="utf-8") as f:
            json.dump(all_prompts, f, indent=2, ensure_ascii=False)
        print(f"\n✓ Saved prompts to: {output_file}")
    
    print("\n" + "="*80)
    print("Prompt extraction complete")
    print("="*80)
    
    return 0


if __name__ == "__main__":
    sys.exit(main())

